---
- name: Create EC2 Instance
  ec2:
    key_name: "{{ key_name }}"
    image: "{{ image }}"
    instance_type: t2.micro
    region: "{{ region }}"
    vpc_subnet_id: "{{vpc_subnet_id}}"
    group_id: "{{sec_group}}"
    instance_tags:
      Name: Create-Instance
    wait: true
    count: 1
